"""
    iStreamPlanet Channels API

    This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results.   # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: support@istreamplanet.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.channel_publishing_dash import ChannelPublishingDash
from openapi_client.model.channel_publishing_hls import ChannelPublishingHls
from openapi_client.model.channel_publishing_publish_points import ChannelPublishingPublishPoints
globals()['ChannelPublishingDash'] = ChannelPublishingDash
globals()['ChannelPublishingHls'] = ChannelPublishingHls
globals()['ChannelPublishingPublishPoints'] = ChannelPublishingPublishPoints
from openapi_client.model.channel_publishing_publications import ChannelPublishingPublications


class TestChannelPublishingPublications(unittest.TestCase):
    """ChannelPublishingPublications unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelPublishingPublications(self):
        """Test ChannelPublishingPublications"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChannelPublishingPublications()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
