"""
    iStreamPlanet Channels API

    This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results.   # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: support@istreamplanet.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.sources_api import SourcesApi  # noqa: E501


class TestSourcesApi(unittest.TestCase):
    """SourcesApi unit test stubs"""

    def setUp(self):
        self.api = SourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_source(self):
        """Test case for get_source

        Get Source  # noqa: E501
        """
        pass

    def test_list_sources(self):
        """Test case for list_sources

        List Sources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
