"""
    iStreamPlanet Channels API

    This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results.   # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: support@istreamplanet.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.channels_api import ChannelsApi  # noqa: E501


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_channel(self):
        """Test case for delete_channel

        Delete channel  # noqa: E501
        """
        pass

    def test_get_channel(self):
        """Test case for get_channel

        Get Channel  # noqa: E501
        """
        pass

    def test_get_playback_config(self):
        """Test case for get_playback_config

        Get Channel Playback Config  # noqa: E501
        """
        pass

    def test_list_channels(self):
        """Test case for list_channels

        List channels  # noqa: E501
        """
        pass

    def test_put_channel(self):
        """Test case for put_channel

        Create/Update channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
