"""
    iStreamPlanet Channels API

    This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results.   # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: support@istreamplanet.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.audit_operations_api import AuditOperationsApi  # noqa: E501


class TestAuditOperationsApi(unittest.TestCase):
    """AuditOperationsApi unit test stubs"""

    def setUp(self):
        self.api = AuditOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_channel_timeline(self):
        """Test case for get_channel_timeline

        Get Channel Timeline  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
