"""
    iStreamPlanet Channels API

    This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results.   # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: support@istreamplanet.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.channel import Channel
from openapi_client.model.channel_playback import ChannelPlayback
from openapi_client.model.error_model import ErrorModel
from openapi_client.model.put_channel_request import PutChannelRequest
from openapi_client.model.summary_list2 import SummaryList2


class ChannelsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.delete_channel_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'authcode',
                    'm2m'
                ],
                'endpoint_path': '/v2/channels/{channel-id}',
                'operation_id': 'delete_channel',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'channel_id',
                    'if_unmodified_since',
                    'if_match',
                    'if_none_match',
                    'if_modified_since',
                ],
                'required': [
                    'channel_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'channel_id',
                ]
            },
            root_map={
                'validations': {
                    ('channel_id',): {
                        'max_length': 60,
                        'regex': {
                            'pattern': r'^([a-z0-9]+(-*[a-z0-9]+)*)$',  # noqa: E501
                        },
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'channel_id':
                        (str,),
                    'if_unmodified_since':
                        (datetime,),
                    'if_match':
                        ([str],),
                    'if_none_match':
                        ([str],),
                    'if_modified_since':
                        (datetime,),
                },
                'attribute_map': {
                    'channel_id': 'channel-id',
                    'if_unmodified_since': 'If-Unmodified-Since',
                    'if_match': 'If-Match',
                    'if_none_match': 'If-None-Match',
                    'if_modified_since': 'If-Modified-Since',
                },
                'location_map': {
                    'channel_id': 'path',
                    'if_unmodified_since': 'header',
                    'if_match': 'header',
                    'if_none_match': 'header',
                    'if_modified_since': 'header',
                },
                'collection_format_map': {
                    'if_match': 'csv',
                    'if_none_match': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.get_channel_endpoint = _Endpoint(
            settings={
                'response_type': (Channel,),
                'auth': [
                    'authcode',
                    'm2m'
                ],
                'endpoint_path': '/v2/channels/{channel-id}',
                'operation_id': 'get_channel',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'channel_id',
                    'if_match',
                    'if_none_match',
                    'if_modified_since',
                    'if_unmodified_since',
                ],
                'required': [
                    'channel_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'channel_id',
                ]
            },
            root_map={
                'validations': {
                    ('channel_id',): {
                        'max_length': 60,
                        'regex': {
                            'pattern': r'^([a-z0-9]+(-*[a-z0-9]+)*)$',  # noqa: E501
                        },
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'channel_id':
                        (str,),
                    'if_match':
                        ([str],),
                    'if_none_match':
                        ([str],),
                    'if_modified_since':
                        (datetime,),
                    'if_unmodified_since':
                        (datetime,),
                },
                'attribute_map': {
                    'channel_id': 'channel-id',
                    'if_match': 'If-Match',
                    'if_none_match': 'If-None-Match',
                    'if_modified_since': 'If-Modified-Since',
                    'if_unmodified_since': 'If-Unmodified-Since',
                },
                'location_map': {
                    'channel_id': 'path',
                    'if_match': 'header',
                    'if_none_match': 'header',
                    'if_modified_since': 'header',
                    'if_unmodified_since': 'header',
                },
                'collection_format_map': {
                    'if_match': 'csv',
                    'if_none_match': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.get_playback_config_endpoint = _Endpoint(
            settings={
                'response_type': (ChannelPlayback,),
                'auth': [
                    'authcode',
                    'm2m'
                ],
                'endpoint_path': '/v2/channels/{channel-id}/playback',
                'operation_id': 'get_playback_config',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'channel_id',
                ],
                'required': [
                    'channel_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'channel_id',
                ]
            },
            root_map={
                'validations': {
                    ('channel_id',): {
                        'max_length': 60,
                        'regex': {
                            'pattern': r'^([a-z0-9]+(-*[a-z0-9]+)*)$',  # noqa: E501
                        },
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'channel_id':
                        (str,),
                },
                'attribute_map': {
                    'channel_id': 'channel-id',
                },
                'location_map': {
                    'channel_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.list_channels_endpoint = _Endpoint(
            settings={
                'response_type': (SummaryList2,),
                'auth': [
                    'authcode',
                    'm2m'
                ],
                'endpoint_path': '/v2/channels',
                'operation_id': 'list_channels',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'page_size',
                    'cursor',
                    'q',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'page_size',
                    'q',
                ]
            },
            root_map={
                'validations': {
                    ('page_size',): {

                        'inclusive_maximum': 100,
                        'inclusive_minimum': 1,
                    },
                    ('q',): {
                        'max_length': 256,
                        'min_length': 3,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'page_size':
                        (int,),
                    'cursor':
                        (str,),
                    'q':
                        (str,),
                },
                'attribute_map': {
                    'page_size': 'page_size',
                    'cursor': 'cursor',
                    'q': 'q',
                },
                'location_map': {
                    'page_size': 'query',
                    'cursor': 'query',
                    'q': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.put_channel_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'authcode',
                    'm2m'
                ],
                'endpoint_path': '/v2/channels/{channel-id}',
                'operation_id': 'put_channel',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'channel_id',
                    'if_match',
                    'if_none_match',
                    'if_modified_since',
                    'if_unmodified_since',
                    'validate_only',
                    'put_channel_request',
                ],
                'required': [
                    'channel_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'channel_id',
                ]
            },
            root_map={
                'validations': {
                    ('channel_id',): {
                        'max_length': 60,
                        'regex': {
                            'pattern': r'^([a-z0-9]+(-*[a-z0-9]+)*)$',  # noqa: E501
                        },
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'channel_id':
                        (str,),
                    'if_match':
                        ([str],),
                    'if_none_match':
                        ([str],),
                    'if_modified_since':
                        (datetime,),
                    'if_unmodified_since':
                        (datetime,),
                    'validate_only':
                        (bool,),
                    'put_channel_request':
                        (PutChannelRequest,),
                },
                'attribute_map': {
                    'channel_id': 'channel-id',
                    'if_match': 'If-Match',
                    'if_none_match': 'If-None-Match',
                    'if_modified_since': 'If-Modified-Since',
                    'if_unmodified_since': 'If-Unmodified-Since',
                    'validate_only': 'validate_only',
                },
                'location_map': {
                    'channel_id': 'path',
                    'if_match': 'header',
                    'if_none_match': 'header',
                    'if_modified_since': 'header',
                    'if_unmodified_since': 'header',
                    'validate_only': 'query',
                    'put_channel_request': 'body',
                },
                'collection_format_map': {
                    'if_match': 'csv',
                    'if_none_match': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/problem+json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def delete_channel(
        self,
        channel_id,
        **kwargs
    ):
        """Delete channel  # noqa: E501

        Delete a channel and stop publishing.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_channel(channel_id, async_req=True)
        >>> result = thread.get()

        Args:
            channel_id (str): Unique channel identifier

        Keyword Args:
            if_unmodified_since (datetime): Succeeds if the server's resource date is older or the same as the passed date.. [optional]
            if_match ([str]): Succeeds if the server's resource matches one of the passed values.. [optional]
            if_none_match ([str]): Succeeds if the server's resource matches none of the passed values. On writes, the special value * may be used to match any existing value.. [optional]
            if_modified_since (datetime): Succeeds if the server's resource date is more recent than the passed date.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['channel_id'] = \
            channel_id
        return self.delete_channel_endpoint.call_with_http_info(**kwargs)

    def get_channel(
        self,
        channel_id,
        **kwargs
    ):
        """Get Channel  # noqa: E501

        Get a channel's configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_channel(channel_id, async_req=True)
        >>> result = thread.get()

        Args:
            channel_id (str): Unique channel identifier

        Keyword Args:
            if_match ([str]): Succeeds if the server's resource matches one of the passed values.. [optional]
            if_none_match ([str]): Succeeds if the server's resource matches none of the passed values. On writes, the special value * may be used to match any existing value.. [optional]
            if_modified_since (datetime): Succeeds if the server's resource date is more recent than the passed date.. [optional]
            if_unmodified_since (datetime): Succeeds if the server's resource date is older or the same as the passed date.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            Channel
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['channel_id'] = \
            channel_id
        return self.get_channel_endpoint.call_with_http_info(**kwargs)

    def get_playback_config(
        self,
        channel_id,
        **kwargs
    ):
        """Get Channel Playback Config  # noqa: E501

        Get a channel's playback configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_playback_config(channel_id, async_req=True)
        >>> result = thread.get()

        Args:
            channel_id (str): Unique channel identifier

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ChannelPlayback
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['channel_id'] = \
            channel_id
        return self.get_playback_config_endpoint.call_with_http_info(**kwargs)

    def list_channels(
        self,
        **kwargs
    ):
        """List channels  # noqa: E501

        Get a list of your channels.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_channels(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            page_size (int): Number of items to return. [optional] if omitted the server will use the default value of 100
            cursor (str): Current page cursor. [optional]
            q (str): Search query to match against for filtering a list of channels. This searches the channel ID, name, labels, and source ID.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            SummaryList2
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        return self.list_channels_endpoint.call_with_http_info(**kwargs)

    def put_channel(
        self,
        channel_id,
        **kwargs
    ):
        """Create/Update channel  # noqa: E501

        Create or update an existing channel configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.put_channel(channel_id, async_req=True)
        >>> result = thread.get()

        Args:
            channel_id (str): Unique channel identifier

        Keyword Args:
            if_match ([str]): Succeeds if the server's resource matches one of the passed values.. [optional]
            if_none_match ([str]): Succeeds if the server's resource matches none of the passed values. On writes, the special value * may be used to match any existing value.. [optional]
            if_modified_since (datetime): Succeeds if the server's resource date is more recent than the passed date.. [optional]
            if_unmodified_since (datetime): Succeeds if the server's resource date is older or the same as the passed date.. [optional]
            validate_only (bool): Validate request but do not otherwise process it. [optional]
            put_channel_request (PutChannelRequest): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['channel_id'] = \
            channel_id
        return self.put_channel_endpoint.call_with_http_info(**kwargs)

